### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by prototux** [vantyaevserega/EmulateBSIPSA#1]
Hello, and thanks for your project :slightly_smiling_face:

It's great to see that the work we have done on PSA's CAN bus is useful!

If you need any more information for your EMF, and how to emulate the BSI, you can also check out the simulator that can emulate the BSI and send EMF frames as well: https://github.com/OpenLeo/simulator

There's also more information for the EMF that's is in the process ot be published, but it takes time to write the yaml files, in the meantime, you can check out our discord server as well (there's people from all over the world, including russia): https://discord.gg/DPthrN2cbS

One of the projects you may be interested in is a C library to talk with PSA's CAN buses, there was an attempt here: https://github.com/prototux/libpsa but the architecture is not good enough, so i'm rewriting it when i have time to.

---

Здравствуйте, и спасибо за ваш проект: :slightly_smiling_face: 

Приятно видеть, что работа, которую мы сделали на автобусе PSA, могут быть полезны!

Если вам нужна дополнительная информация для вашей EMF, и как эмулировать BSI, вы также можете проверить симулятор, который может эмулировать BSI и отправлять кадры EMF: https://github.com/Openleo/simulator

Существует также дополнительная информация для EMF, которая находится в процессе, который находится в процессе, но требуется время, чтобы написать файлы yaml, в то же время вы можете также проверить наш сервер раздора (есть люди со всего мира, включая Россию ): https://discord.gg/dpthrn2cbs.

Один из проектов, которые вас могут быть заинтересованы в том, это C Bibreate, чтобы поговорить с автобусами PSA Can, здесь была попытка: https://github.com/prototux/libpsa, но архитектура недостаточно хороша, поэтому я переписываю Это когда у меня есть время.

**Comment by vantyaevserega** [comment]
Oh, thank you! It's great that the project has been noticed. In fact, he is already a little more. Now I'm testing my adapter for the head unit on android, but it's too early to post it, it's too raw.
I'm already looking at your projects, there is another project that helps me: https://autowp.github.io/

**Comment by prototux** [comment]
If you switch your head unit to andoid, you may want to check the 21F frame for the wheel controls :wink: 

One of the early versions of the psa-re repository was actually a generator for autowp's html page (https://github.com/prototux/PSA-CAN-RE-old/tree/master/old_doc), but now there's way too much data to display it all on a single page like autowp (there's hundreds of CAN frames in total, for each of the generations).

There's a lot more documentation coming in the future, but in the meantime don't hesitate to ask (especially on the discord, as i'm definitively not alone working on it) if you need some infos on some specific frames, i can check if i have information on them :slightly_smiling_face:

**Comment by vantyaevserega** [comment]
Yes, I check 21F, also check A2 steering frame. But this is not enough, since there are still buttons at the bottom left of the steering wheel on the Citroen c4 1 generation.
Now I'm thinking about the fact that it's easier to add LIN bus processing for polling buttons.
Thanks for the help. Actually there is 1 question. I often see in the documentation that frame 39B can set the time, and frame 276 returns the time and date. In practice, frame 39B does not change anything in my case, and frame 276 returns the display time from the first start, and this is not enough to find out the time on the car's EMF display. Is there any other way to get the current time? I want to make the backlight control of the head unit based on this time and date.

**Comment by prototux** [comment]
The buttons on the steering wheels are probably the VMF, so not the same CAN frames than the 21F. the VMF frames includes the 0A2, but also the 0ED, 082 and some bits on the 094 (the vocal button is probably the same bit as the push button on the blinker lever on 094.

I don't think there's any 39B nor 276 on AEE2004 ECUs, there's the first 3 bytes of 3F6 that the EMF sends with it's configured date, AFAIK the C4 doesn't have the fake analog clock (only on RCZ for this generation) so i think the only date you can find is on 3F6 (seconds since powered on, day, and year, respectively for the 3 first bytes, it's a strange format). Other than that, there's no device that keeps time on AEE2004 cars as far as i can tell.

**Comment by vantyaevserega** [comment]
Thanks for the replies, it's much clearer now.

**Comment by prototux** [comment]
Great! i'll close the issue then :slightly_smiling_face: 

If you have any other questions you can ask directly on the PSA-RE repository, or even better (as there will be more people that could answer), on the OpenLeo's discord server
